### ISSUE TITLE
Skull & Crossbones

### ISSUE THREAD

**Issue by RobLoach** [libretro-thumbnails/MAME#3]
https://github.com/libretro-thumbnails/libretro-thumbnails/commit/3fc64eee47f5f7f6a28078c0eda822c9ea2fc34e

They should be part of this repo.

**Comment by alfrix** [comment]
Did it c52030a

Please fix the history of libretro-thumbnails/libretro-thumbnails since i can´t force push
`git push origin +3fc64eee^:master`
